# ===============================
# = PRODUCTION ENVIRONMENT CONFIG
# ===============================

# ===============================
# = DATABASE CONFIGURATION
# ===============================
spring:
  # Database connection - use environment variables in production
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20
      minimum-idle: 10
  
  # JPA/Hibernate
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

# ===============================
# = LOGGING CONFIGURATION
# ===============================
logging:
  level:
    root: WARN
    com.ligera.backend: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    
# ===============================
# = REDIS CONFIGURATION
# ===============================
spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    
# ===============================
# = SECURITY CONFIGURATION
# ===============================
app:
  jwt:
    secret: ${JWT_SECRET}
  
  # CORS configuration for production
  cors:
    # Restrict to specific domains in production
    allowed-origins: https://ligera.com,https://app.ligera.com,https://www.ligera.com
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: Authorization,Content-Type,X-Requested-With
    exposed-headers: Authorization
    allow-credentials: false
    max-age: 3600
    
# ===============================
# = RATE LIMITING CONFIGURATION
# ===============================
rate:
  limit:
    enabled: true
    capacity:
      anonymous: 20    # More strict in production
      authenticated: 40

# ===============================
# = PRODUCTION CONFIGURATION
# ===============================

# ===============================
# = DATABASE CONFIGURATION
# ===============================
spring:
  # Database connection - use environment variables in production
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    # Connection pool - optimized for production
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000

  # JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

# ===============================
# = LOGGING CONFIGURATION
# ===============================
logging:
  level:
    root: WARN
    com.ligera.backend: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN

# ===============================
# = PRODUCTION SPECIFIC SETTINGS
# ===============================
server:
  tomcat:
    max-threads: 200
    min-spare-threads: 20
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json

# CORS configuration for production
app:
  cors:
    # Restrict to specific domains in production
    allowed-origins: https://ligera.com,https://app.ligera.com
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: Authorization,Content-Type,X-Requested-With
    exposed-headers: Authorization
    allow-credentials: false
    max-age: 3600

